name: Deployments Core CI

env:
  CI: true

on:
  push:
    branches: "*"
    paths:
      - packages/core/**
  pull_request:
    branches: "*"
    paths:
      - packages/core/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn workspace @mimic-fi/v3-deployments-core lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn workspace @mimic-fi/v3-deployments-core test
